### ISSUE TITLE
Use `attrs` for lots of the return values

### ISSUE THREAD

**Issue by thht** [schmidtfa/pyrasa#15]
There are lots of functions that currently return a tuple. Let's think about them returning dataclasses with [`attrs`](https://www.attrs.org/en/stable/).

**Comment by schmidtfa** [comment]
I like and will open a branch

**Comment by schmidtfa** [comment]
I have some second thoughts here. While I like the idea of returning data classes. I would prefer increases in speed, if possible. In case Cython or mypyc #25 dont result in proper speed-ups and/or seem like a pain to maintain relative to performance I am happy to go in the direction of attrs. What are your thoughts on this @thht ?

**Comment by schmidtfa** [comment]
ok this makes sense!
